Creacion de la seccion 2 y ajustes de responsive para pantallas mas …
AJimenezHolguin/Swipe pull request #2
Opened 2023-07-20 20:38 UTC by AJimenezHolguin

…grandes

2023-07-21 16:13 UTC, DanielCalleCO requested changes
Te está quedando buenísimo! felicitaciones mi hermano

2023-07-21 16:13 UTC, DanielCalleCO commented on styles2.css
>      width: 650px;
te recomiendo que no le pongas un width a tu imagen porque en 768px y luego de 1024, parece que la hubieras alargado por los cachetes jajajaja

![image](https://github.com/AJimenezHolguin/Swipe/assets/100431019/97ab46a1-d34b-4887-aa93-13dffe9322cb)


Te puedo recomendar 2 cosas...

1. Coloca la imagen dentro de un div y a esa si dale tamaño (si necesitas un ancho especifico)
2. Solo ajustale el alto a la imagen y deja el width automático.

2023-07-23 00:05 UTC, AJimenezHolguin commented on styles2.css
>      width: 650px;
Buenas noches mi hermano se realizan los ajustes solicitados tanta para la imagen de la sección 1 como para las imagenes de la seccion 2 donde tambien parecian que se les estuviera halando los cachetes jejeje... por favor revisar y validar.

2023-07-23 12:27 UTC, DanielCalleCO commented
Recuerda darle click donde dice `Resolve conversation` aquí en GitHub una vez ya hayas resuelto los comentarios que te hice, sino no, nos deja hacer el merge!
![image](https://github.com/AJimenezHolguin/Swipe/assets/100431019/8c93b4ab-0a47-4180-a0bf-aba5a770ce08)

2023-07-23 12:29 UTC, DanielCalleCO commented
![image](https://github.com/AJimenezHolguin/Swipe/assets/100431019/d1784ac1-4aeb-48a2-9821-9034175ea271)

Creo que este espacio no se ve bien repartido... que dices, hay como mucho espacio debajo del ultimo texto de la derecha... o es solo mi impresión?

2023-07-23 12:31 UTC, DanielCalleCO commented
Aunque en 1024 se ve bien! Es solo una bobadita para que se vea bien en todas las resoluciones, pero como en 1024 está bien, lo apruebo... solo que si le puedes echar un ojo luego de que terminemos el reto, sería genial!

![image](https://github.com/AJimenezHolguin/Swipe/assets/100431019/70812484-b445-4434-bcd8-83bcd30e3938)

2023-07-23 12:33 UTC, DanielCalleCO commented
Pregunta... te gusta cómo se esa linea que divide la sección 1 de la 2?

![image](https://github.com/AJimenezHolguin/Swipe/assets/100431019/a53a217c-f9e7-450b-899b-aa6bbd73d8a6)

Si dices SI, te apruebo, si dices NO, te aconsejo dejar la sección 2 y el reto de la página con fondo blanco y aprobamos!

2023-07-23 18:00 UTC, AJimenezHolguin commented
buenos tardes, profe esa linea que divide las dos secciones asi también esta en la original. yo la veo bien pordriamos aprobar y como dices tu cuando terminemos el bootcamp hacer las mejoras correspondientes para las pantallas mas grandes, de 1024 en adelante.

2023-07-23 18:59 UTC, DanielCalleCO commented
@AJimenezHolguin es solo eliminar la linea 102, o en su defecto ponerle a `background-section_2 {background-color: #fff}` en vez de f7f9fc la verdad no se ve lindo y pues es cierto que está en el orginial, pero incluso el original es una copia de otra página... Y cuando venga alguien a ver tu portafolia y vea la página con esas cosas, no va a pensar que lo hiciste tal cual a Juangui, sino que va a pensar (probablemente) a este man, esta sección le quedó diferente al fondo...

2023-07-23 19:00 UTC, DanielCalleCO commented
![image](https://github.com/AJimenezHolguin/Swipe/assets/100431019/73d97dea-a01c-4608-964c-013bdae8da86)

Estas imágenes no me salen, creo que se te fue otra vez el "/" antes de assets

2023-07-23 19:02 UTC, DanielCalleCO requested changes
![image](https://github.com/AJimenezHolguin/Swipe/assets/100431019/24d38011-a2df-4713-b8d6-5d8adaf75191)
O le aplicas height o le aplicas width, pero cuando le aplicas ambas, se ven como si mario bros se le hubiera parado encima jajajaja

2023-07-23 19:36 UTC, AJimenezHolguin commented
profe acabo  de realizar cambios en la sección 2 elimine el background de todas la pantallas mobile, tablet, desktop y mayores a 1365px.
con respecto a las imagenes las tengo sin "/ " podría ser la ubicación de los assets en tu equipo profe.
(no se si puedas visualizar la imagen que te envío aqui)
![image](https://github.com/AJimenezHolguin/Swipe/assets/122332192/545746a7-729b-4424-a6d2-9046bcc5e7c2)

2023-07-23 19:42 UTC, DanielCalleCO commented
![image](https://github.com/AJimenezHolguin/Swipe/assets/100431019/24ae3647-743d-41bc-a698-19ee7902a643)
a estas dos ultimas imagenes les estás aplicando height y width y te está quedando mal... quitale el height en la linea 175 y en la linea 181 y miras si todo te queda bien y envías cambio para aprobar por fa

2023-07-23 20:12 UTC, AJimenezHolguin commented
Se realizan cambios  en las imagenes donde se deja un width:100% para mobile y en pantallas como tablet, desktop y mayores a 1365px se elimina el width y 
se ajusta un height al 100% para visualizar bien las imagenes en todas las pantallas

2023-07-23 20:22 UTC, DanielCalleCO commented
Mira como se ve en 320px
![image](https://github.com/AJimenezHolguin/Swipe/assets/100431019/b17912d2-ace7-4dd7-a02a-fd9fc3a7df7b)

2023-07-23 20:25 UTC, DanielCalleCO commented
![image](https://github.com/AJimenezHolguin/Swipe/assets/100431019/d4c21f20-8d09-4393-93cb-285dfc54c1e6)

Parce, creo que se siguen viendo estiradas esas imagenes... o soy yo?

2023-07-23 20:31 UTC, AJimenezHolguin commented
Profe me base en la página origina donde en 320px muestra las imagenes asi pero dime si quieres que las modifique y las ponga en columna o que no se muestren en ese tampo de pantalla.
![image](https://github.com/AJimenezHolguin/Swipe/assets/122332192/39849eb4-b8da-46df-98bb-368bfe5ed8d0)
Y lo otro porfe podríamos conectarnos para validar lo del tamaño de las otras imagenes porque ahi estan ajustadas al tamaño del contenedor yo creo que por eso se pueden ver alargadas o anchas.

2023-07-24 14:07 UTC, DanielCalleCO commented
Aprobado PERO en 1024 mira como salen tus imagenes... 
![image](https://github.com/AJimenezHolguin/Swipe/assets/100431019/a2002dfd-033f-43c1-b650-39aaf04458ff)

Soluciona eso después de la sección 4... avanza lo más rápido que puedas HOY!

2023-07-24 14:09 UTC, DanielCalleCO approved these changes
Aprobado con cambios para hacer luego de la sección 4

2023-07-24 17:18 UTC, merged